config/routes.rb
Rails.application.routes.draw do

  resources :projects #URLを自動生成してくれる的な

  root 'projects#index' ##http://localhost:3000にアクセスしたときにこれを呼び出す

end

app/models/project.rb
class Project < ActiveRecord::Base
	# validates :title, presence: true //can't be blank みたいなのがデフォルトで出る
	validates :title, presence: {message: "入力してください"},
	length: {minimum: 3, message: "短すぎ"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@projects = Project.all #@をつけるとViewでも使える
		@url = [createURL(125647),createURL(309277)]
		render :index
	end

	# GET /projects/:id
	def show
		@project = Project.find(params[:id])
		#urlで渡ってきた数字をparamsで取れる
		render :show
	end

	def new
		@project = Project.new
		# render :new
	end

	def create
		@project = Project.new(project_params)
		if  #セーブがうまく行ったとき(入力があったとき)
			@project.save
			redirect_to projects_path
		else 
			render 'new'
		end
	end

	def edit
		@project = Project.find(params[:id])
	end

	def update
		@project = Project.find(params[:id])
		if 
			@project.update(project_params)
			redirect_to projects_path
		else
			render 'edit'
		end
	end

	def destroy #delete処理
		@project = Project.find(params[:id])
		@project.destroy
		redirect_to projects_path
	end

	#保存する仕組みはvalidationで制御
	private #セキュリティのためにするようになったらしいフィルター的な
		def project_params
			params[:project].permit(:title)
		end

	def createURL(id)
		str1 = "https://lvimg.jp/job/img/job_pict/"
		str2 = (id%100).to_s 
		str3 = "/"
		str4 = id.to_s
		str5 = "/big.jpg/180x135-f1"
		str=str1+str2+str3+str4+str5
		return str
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taskapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<!-- <%= link_to "Home","/" %> -->
<%= link_to "Home",projects_path %>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

<p>
	<%= f.label :title%><br>
	<%= f.text_field :title%>
	<% if @project.errors.any? %>
	<%= @project.errors.messages[:title][0] %>
	<% end %>
</p>

<p>
	<%= f.submit %>
</p>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit</h1>

<!-- ここのフォームが優秀なので勝手にupdateとかにしといてくれたり、フォームに現在の情報を入れてたりしてくれる -->

<%= render 'form'%>
<!-- #UnOrdered List リストの大枠%=にするとrubyの評価をhtmlに埋め込む的な-->

app/views/projects/index.html.erb
<h1>Projects</h1>
<ul>
	<% @projects.each do |project| %>
	<li>
		<!-- <%= link_to project.title ,project_path(project.id) %> -->
		<% @url.each do |url| %>
		<img src= "<%=url%>" >
		<% end %>
		<%= link_to project.title ,project_path(project) %>
		<%= link_to "[Edit]", edit_project_path(project.id)%>
		<%= link_to "[Delete]", project_path(project.id), method: :delete,data: {confirm: "are you sure?"} %>
	</li>
	<% end %>

<ul>

<p>
	<%= link_to "Add New", new_project_path %>
</p>
<!-- #UnOrdered List リストの大枠 
%= にするとrubyの評価をhtmlに埋め込む的な
-->

app/views/projects/new.html.erb
<h1>Add New</h1>

<%= render 'form'%>
<!-- #UnOrdered List リストの大枠%=にするとrubyの評価をhtmlに埋め込む的な-->

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>